import { useState } from "react";
import "../index.css";
import StudentNavbar from "./StudentNavbar.jsx";

export default function StudentAbout({ onLogout, onNavigate }) {
  const [showMore, setShowMore] = useState(false);

  return (
    <div className="dashboard">
      <StudentNavbar
        onLogout={onLogout}
        onNavigate={onNavigate}
        active="about"
      />

      {/* Page content */}
      <main className="about-page container">
        <h1 className="about__title">Welcome to BukSU CoT Thesis Realm</h1>

        <section className="about__intro">
          <p>
            The BukSU CoT Thesis Realm is a comprehensive digital repository
            designed to preserve, showcase, and share the outstanding academic
            work produced by students and faculty at Bukidnon State University
            College of Technology.
          </p>
          <p>
            Our platform is a centralized hub where researchers, students, and
            educators can easily access, browse, and explore thesis and capstone
            projects across engineering and technology disciplines. By
            digitizing and organizing academic research, we enhance knowledge
            discovery, promote collaboration, and inspire innovation.
          </p>

          {showMore && (
            <p>
              Whether you’re a student seeking inspiration, a faculty member
              reviewing previous work, or an external researcher, the Thesis
              Realm provides an intuitive and efficient way to explore the
              knowledge generated by our academic community.
            </p>
          )}

          <button
            className="about__toggle link"
            onClick={() => setShowMore((v) => !v)}
          >
            {showMore ? "Show less" : "Read more"}
          </button>
        </section>

        <section className="about__cards">
          <article className="card about-card">
            <div className="card__icon">
              <svg viewBox="0 0 24 24" width="26" height="26" aria-hidden="true">
                <circle
                  cx="12"
                  cy="12"
                  r="9"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="1.6"
                />
                <circle
                  cx="12"
                  cy="12"
                  r="5"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="1.6"
                />
                <circle cx="12" cy="12" r="2.2" fill="currentColor" />
              </svg>
            </div>
            <h3 className="card__title">Our Mission</h3>
            <p className="card__text">
              Create a centralized, accessible platform that showcases the
              academic excellence and innovative research of BukSU College of
              Technology—making knowledge sharing seamless and efficient.
            </p>
          </article>

          <article className="card about-card">
            <div className="card__icon">
              <svg viewBox="0 0 24 24" width="26" height="26" aria-hidden="true">
                <path
                  d="M16 14a4 4 0 1 0-8 0M4 20a6 6 0 0 1 16 0"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="1.6"
                />
                <circle
                  cx="15"
                  cy="7"
                  r="3"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="1.6"
                />
                <circle
                  cx="7"
                  cy="9"
                  r="3"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="1.6"
                />
              </svg>
            </div>
            <h3 className="card__title">Community Driven</h3>
            <p className="card__text">
              Built by students, for students and faculty. We foster
              collaboration and knowledge exchange within our academic
              community, encouraging continuous learning and innovation.
            </p>
          </article>
        </section>
      </main>
    </div>
  );
}
